{% set name = "jupyterlab-spreadsheet-editor" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jupyterlab_spreadsheet_editor-{{ version }}.tar.gz
  sha256: ded8ca3d845dae906a7e7b323f8140a71994a8d64095de165ace217e682ad3b3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.5.0
    - jupyterlab >=4.0.0,<5.0.0dev0
    - hatch-nodejs-version >=0.3.2
    - hatch-jupyter-builder >=0.5
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - jupyterlab >=4.0.0,<5.0.0dev0

test:
  imports:
    - jupyterlab_spreadsheet_editor
  commands:
    - pip check
    - jupyter labextension list
    - jupyter labextension list 1>labextensions 2>&1
    - cat labextensions | grep "spreadsheet-editor.*OK"  # [unix]
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jupyterlab-contrib/jupyterlab-spreadsheet-editor.git
  summary: JupyterLab spreadsheet (csv/tsv) editor
  license: CC0-1.0 AND BSD-3-Clause
  license_file:
    - LICENSE
    - style/icons/LICENSE

extra:
  recipe-maintainers:
    - maresb
    - drhagen
    - krassowski
